export * from "./decrator";
export * from "./iStrategy";
export * from "./watch";
export * from "./ast";
export * from "./utils";
export * from "./parse";
export * from "./loadObject/scan";
export * from "./loadObject/require";
export * from "./loadObject/flatten";
export declare function runCli(rest: any): void;
export declare function run(rest: any): void;
