export * from "./Decrator";
export * from "./IStrategy";
export * from "./Watch";
export * from "./Ast";
export * from "./Utils";
export * from "./parse";
export * from "./loadObject/scan";
export * from "./loadObject/require";
export * from "./loadObject/flatten";
export declare function executeWithDefaultStrategy(dirs: string[]): void;
export declare function executeFileWithDefaultStrategy(testFiles: string[]): void;
export declare function execute(rest: any): void;
